// <auto-generated />
namespace vls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class editedtheagentbranchtableagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editedtheagentbranchtableagain));
        
        string IMigrationMetadata.Id
        {
            get { return "201501111755068_edited the agent branch table again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
