// <auto-generated />
namespace vls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddednewModelstothedatacontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddednewModelstothedatacontext));
        
        string IMigrationMetadata.Id
        {
            get { return "201501111528397_Added new Models to the data context"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
